import * as vscode from "vscode";
import type { ParsedFile, WorkspaceIndex } from "../workspace/WorkspaceIndex";
import { getOutputChannel } from "../outputChannel";

/**
 * Singleton webview panel that renders a `tarn run --format html`
 * dashboard generated by the Tarn CLI. The HTML is self-contained
 * (inline CSS + JS + data), so we load it into `webview.html`
 * directly rather than exposing the tmp file via `localResourceRoots`.
 *
 * On top of the Tarn-generated HTML we inject a small JS bridge
 * (see {@link injectReportBridge}) that attaches click handlers to
 * every failing `.step` row and posts a `jumpTo` message back to the
 * extension host. The extension host then resolves the step's YAML
 * range via the `WorkspaceIndex` and opens the file in an editor,
 * landing the cursor on the exact failing step.
 */
export class ReportWebview implements vscode.Disposable {
  private panel: vscode.WebviewPanel | undefined;
  private readonly messageDisposables: vscode.Disposable[] = [];

  constructor(private readonly index: WorkspaceIndex) {}

  /** Render the given HTML in a reused panel (creating one if needed). */
  show(htmlContent: string, title = "Tarn HTML Report"): void {
    if (!this.panel) {
      this.panel = vscode.window.createWebviewPanel(
        "tarn.report",
        title,
        { viewColumn: vscode.ViewColumn.Beside, preserveFocus: false },
        {
          enableScripts: true,
          retainContextWhenHidden: true,
          // No local resource roots: the HTML is fully self-contained
          // and rendered from a string, so there are no file:// loads.
          localResourceRoots: [],
        },
      );
      this.panel.onDidDispose(() => {
        for (const d of this.messageDisposables) {
          d.dispose();
        }
        this.messageDisposables.length = 0;
        this.panel = undefined;
      });
      this.messageDisposables.push(
        this.panel.webview.onDidReceiveMessage((message) =>
          this.handleMessage(message),
        ),
      );
    } else {
      this.panel.title = title;
      this.panel.reveal(vscode.ViewColumn.Beside, false);
    }
    this.panel.webview.html = injectReportBridge(htmlContent);
  }

  /** Exposed for tests — drives the jumpTo branch without a real webview. */
  async handleMessage(message: unknown): Promise<boolean> {
    if (!isJumpToMessage(message)) {
      return false;
    }
    const parsed = findParsedByRelativePath(this.index, message.file);
    if (!parsed) {
      getOutputChannel().appendLine(
        `[tarn] ReportWebview: no parsed file matches ${message.file}`,
      );
      return false;
    }
    const test = parsed.ranges.tests.find((t) => t.name === message.test);
    const step = test?.steps.find((s) => s.index === message.stepIndex);
    const range = step?.nameRange ?? test?.nameRange;
    if (!range) {
      getOutputChannel().appendLine(
        `[tarn] ReportWebview: no range for ${message.file}::${message.test}::${message.stepIndex}`,
      );
      return false;
    }
    const doc = await vscode.workspace.openTextDocument(parsed.uri);
    await vscode.window.showTextDocument(doc, {
      selection: range,
      preserveFocus: false,
      viewColumn: vscode.ViewColumn.One,
    });
    return true;
  }

  dispose(): void {
    for (const d of this.messageDisposables) {
      d.dispose();
    }
    this.panel?.dispose();
    this.panel = undefined;
  }
}

export interface JumpToMessage {
  type: "jumpTo";
  file: string;
  test: string;
  stepIndex: number;
}

function isJumpToMessage(value: unknown): value is JumpToMessage {
  if (!value || typeof value !== "object") return false;
  const m = value as Record<string, unknown>;
  return (
    m.type === "jumpTo" &&
    typeof m.file === "string" &&
    typeof m.test === "string" &&
    typeof m.stepIndex === "number"
  );
}

/**
 * Best-effort lookup of a ParsedFile by the path the Tarn report
 * emitted, which is typically a workspace-relative path. Tries exact
 * match, suffix match, then basename match.
 */
function findParsedByRelativePath(
  index: WorkspaceIndex,
  filePath: string,
): ParsedFile | undefined {
  for (const parsed of index.all) {
    if (parsed.uri.fsPath === filePath) return parsed;
  }
  for (const parsed of index.all) {
    if (parsed.uri.fsPath.endsWith(filePath)) return parsed;
  }
  for (const parsed of index.all) {
    if (
      filePath.endsWith(parsed.uri.fsPath) ||
      basename(parsed.uri.fsPath) === basename(filePath)
    ) {
      return parsed;
    }
  }
  return undefined;
}

function basename(p: string): string {
  const slash = p.lastIndexOf("/");
  return slash >= 0 ? p.slice(slash + 1) : p;
}

/**
 * Inject a small script into the Tarn-generated HTML that wires up
 * "click a failed step → jump to source" via `vscode.postMessage`.
 *
 * The script walks `.file-card[data-file]` and `.test-group[data-test]`
 * elements (which the Tarn HTML reporter already emits) to derive
 * the step_index of each failed `.step` node, so the extension host
 * can resolve the YAML range by (file, testName, stepIndex).
 *
 * Idempotent: if the bridge has already been injected once, the
 * marker comment prevents a second insertion.
 */
export function injectReportBridge(html: string): string {
  if (html.includes(BRIDGE_MARKER)) {
    return html;
  }
  const bridge = `${BRIDGE_MARKER}
<script>
(function() {
  try {
    var vscode = acquireVsCodeApi();
    var data = (typeof window !== "undefined" && window.DATA) || null;
    if (!data || !Array.isArray(data.files)) return;

    document.querySelectorAll(".file-card[data-file]").forEach(function(fileCard) {
      var fi = Number(fileCard.getAttribute("data-file"));
      var file = data.files[fi];
      if (!file) return;
      var filePath = file.file || "";

      fileCard.querySelectorAll(".test-group[data-test]").forEach(function(testGroup) {
        var attr = testGroup.getAttribute("data-test") || "";
        var parts = attr.split("-");
        var ti = Number(parts[1]);
        var test = (file.tests || [])[ti];
        if (!test) return;

        var steps = testGroup.querySelectorAll(".test-group-body > .step");
        steps.forEach(function(stepEl, stepIndex) {
          if (!stepEl.querySelector(".step-icon.fail")) return;
          stepEl.style.cursor = "pointer";
          stepEl.title = "Click to open this step in the editor";
          stepEl.addEventListener("click", function(ev) {
            // Swallow clicks on inner expand/collapse controls and
            // assertion detail rows so only the "body" of the step
            // triggers navigation.
            if (ev.target.closest(".assert-details-toggle, .req-resp-toggle, button, .assert-detail, .req-resp-content")) {
              return;
            }
            vscode.postMessage({
              type: "jumpTo",
              file: filePath,
              test: test.name,
              stepIndex: stepIndex
            });
          });
        });
      });
    });
  } catch (err) {
    // Best-effort — if the report HTML ever drops the data-* hooks
    // the bridge silently becomes a no-op.
    console.error("tarn report bridge failed:", err);
  }
})();
</script>
`;
  if (html.includes("</body>")) {
    return html.replace("</body>", `${bridge}</body>`);
  }
  // Fall back to appending; malformed HTML shouldn't break rendering.
  return `${html}\n${bridge}`;
}

export const BRIDGE_MARKER = "<!-- tarn-vscode-report-bridge -->";
